# green = "#919e8b" rgba(145,158,139,1)
# yellow = "#d7ab82"  rgba(215,171,130,1)
# blue = "#ebd2b9" rgba(235,210,185,1)
# grey = "#6e7074" rgba(110,112,116,1)
# lightblue = "#f6f9fc" rgba(246,249,252,1)
# sepia = "rgba(254,248,239,1)" # sepia yellow

[theme]
primaryColor = "#015796" 
backgroundColor = "lightblue"
secondaryBackgroundColor =  "#0277bd"
textColor = "black"
font ="serif"